


import { Language } from './types';

// CHART_OF_ACCOUNTS is removed as it will be fetched from the API dynamically

export const TRANSLATIONS = {
  ID: {
    dashboard: 'Ringkasan',
    transactions: 'Transaksi',
    approvals: 'Persetujuan',
    reports: 'Laporan',
    settings: 'Pengaturan',
    inventory: 'Laporan Kupon',
    branches: 'Cabang',
    operators: 'Operator',
    totalAsset: 'Total Aset',
    revenue: 'Pendapatan',
    expense: 'Beban',
    netProfit: 'Laba Bersih',
    pendingApprovals: 'Menunggu Persetujuan',
    addTransaction: 'Tambah Transaksi',
    branch: 'Cabang',
    status: 'Status',
    description: 'Keterangan',
    amount: 'Jumlah',
    date: 'Tanggal',
    action: 'Aksi',
    approve: 'Setujui',
    reject: 'Tolak',
    systemConfig: 'Konfigurasi Sistem',
    loginTitle: 'Antarmuka Operasi Aman',
    accessKey: 'Kunci Akses (Username)',
    encryptionKey: 'Kunci Enkripsi (Opsional)',
    authorizeSession: 'Otorisasi Sesi',
    invalidAuth: 'KUNCI OTORISASI SALAH',
    couponCode: 'Kode Kupon',
    refNumber: 'No. Bukti',
    stockIn: 'Stok Masuk',
    stockOut: 'Stok Keluar',
    finalStock: 'Stok Akhir',
    totalIn: 'Total Masuk',
    totalOut: 'Total Keluar',
    inputMutation: 'Input Mutasi Kupon',
    editMutation: 'Edit Laporan',
    save: 'Simpan',
    delete: 'Hapus',
    cancel: 'Batal',
    category: 'Kategori',
    memo: 'Memo / Deskripsi',
    income: 'Pendapatan',
    expense_type: 'Beban',
    kasbon: 'Kasbon',
    close_kas: 'Tutup Kas',
    ledgerCategory: 'Kategori Akun',
    targetBranch: 'Cabang Target',
    cashBalance: 'Saldo Kas',
    valueUsd: 'Nilai (USD)',
    commitEntry: 'Kirim Entri',
    generatePdf: 'Cetak PDF Resmi',
    incomeStatement: 'Laporan Laba Rugi',
    balanceSheet: 'Neraca',
    journal: 'Jurnal Umum',
    printTime: 'Waktu Cetak',
    auditedReport: 'Laporan Teraudit',
    fullName: 'Nama Lengkap',
    role: 'Peran',
    password: 'Kata Sandi',
    newOperator: 'Operator Baru',
    newBranch: 'Cabang Baru',
    location: 'Lokasi',
    companyDetails: 'Detail Perusahaan',
    persistenceLayer: 'Penyimpanan Data',
    backup: 'Cadangkan DB',
    restore: 'Pulihkan',
    chartMatrix: 'Matriks Akun',
    newAccount: 'Akun Baru',
    allBranches: 'SEMUA CABANG',
    mainHq: 'PUSAT',
    secureSession: 'SESI AMAN',
    switchBranch: 'Ganti Cabang',
    sessionLocked: 'Sesi Terkunci otomatis karena tidak aktif'
  },
  EN: {
    dashboard: 'Dashboard',
    transactions: 'Transactions',
    approvals: 'Approvals',
    reports: 'Reports',
    settings: 'Settings',
    inventory: 'Coupon Report',
    branches: 'Branches',
    operators: 'Operators',
    totalAsset: 'Total Assets',
    revenue: 'Revenue',
    expense: 'Expenses',
    netProfit: 'Net Profit',
    pendingApprovals: 'Pending Approvals',
    addTransaction: 'New Transaction',
    branch: 'Branch',
    status: 'Status',
    description: 'Description',
    amount: 'Amount',
    date: 'Date',
    action: 'Action',
    approve: 'Approve',
    reject: 'Reject',
    systemConfig: 'System Configuration',
    loginTitle: 'Secure Operation Interface',
    accessKey: 'Access Key (Username)',
    encryptionKey: 'Encryption Key (Optional)',
    authorizeSession: 'Authorize Session',
    invalidAuth: 'INVALID AUTHORIZATION KEY',
    couponCode: 'Coupon Code',
    refNumber: 'Ref. Number',
    stockIn: 'Stock In',
    stockOut: 'Stock Out',
    finalStock: 'Final Stock',
    totalIn: 'Total In',
    totalOut: 'Total Out',
    inputMutation: 'Input Coupon Mutation',
    editMutation: 'Edit Report',
    save: 'Save',
    delete: 'Delete',
    cancel: 'Cancel',
    category: 'Category',
    memo: 'Memo / Description',
    income: 'Income',
    expense_type: 'Expense',
    kasbon: 'Cash Advance',
    close_kas: 'Close Cash',
    ledgerCategory: 'Ledger Category',
    targetBranch: 'Target Branch',
    cashBalance: 'Cash Balance',
    valueUsd: 'Value (USD)',
    commitEntry: 'Commit Entry',
    generatePdf: 'Generate Official PDF',
    incomeStatement: 'Income Statement',
    balanceSheet: 'Balance Sheet',
    journal: 'General Ledger',
    printTime: 'Print Time',
    auditedReport: 'Audited Report',
    fullName: 'Full Name',
    role: 'Role',
    password: 'Password',
    newOperator: 'New Operator',
    newBranch: 'New Branch',
    location: 'Location',
    companyDetails: 'Company Details',
    persistenceLayer: 'Persistence Layer',
    backup: 'Backup DB',
    restore: 'Restore',
    chartMatrix: 'Chart Matrix',
    newAccount: 'New Account',
    allBranches: 'ALL BRANCHES',
    mainHq: 'HEADQUARTERS',
    secureSession: 'SECURE SESSION',
    switchBranch: 'Switch Branch',
    sessionLocked: 'Session auto-locked due to inactivity'
  },
  TET: {
    dashboard: 'Rezumu',
    transactions: 'Transasaun',
    approvals: 'Aprovasaun',
    reports: 'Relatóriu',
    settings: 'Konfigurasaun',
    inventory: 'Relatóriu Kupón',
    branches: 'Sukurzál',
    operators: 'Operadór',
    totalAsset: 'Totál Ativu',
    revenue: 'Rendimentu',
    expense: 'Kustu',
    netProfit: 'Laba Lihun',
    pendingApprovals: 'Hein Aprovasaun',
    addTransaction: 'Transasaun Foun',
    branch: 'Sukurzál',
    status: 'Status',
    description: 'Deskrisaun',
    amount: 'Montante',
    date: 'Data',
    action: 'Asaun',
    approve: 'Aprova',
    reject: 'Rejeita',
    systemConfig: 'Konfigurasaun Sistema',
    loginTitle: 'Interface Operasaun Seguru',
    accessKey: 'Xave Asesu (Username)',
    encryptionKey: 'Xave Enkripsaun (Opsionál)',
    authorizeSession: 'Autoriza Sesaun',
    invalidAuth: 'XAVE AUTORIZASAUN SALA',
    couponCode: 'Kódigu Kupón',
    refNumber: 'Númeru Prova',
    stockIn: 'Kupón Tama',
    stockOut: 'Kupón Sai',
    finalStock: 'Stoke Ikus',
    totalIn: 'Totál Tama',
    totalOut: 'Totál Sai',
    inputMutation: 'Input Mutasaun Kupón',
    editMutation: 'Edit Relatóriu',
    save: 'Rai',
    delete: 'Hamos',
    cancel: 'Kansela',
    category: 'Kategoria',
    memo: 'Memo / Deskrisaun',
    income: 'Rendimentu',
    expense_type: 'Kustu',
    kasbon: 'Kasbon',
    close_kas: 'Taka Kas',
    ledgerCategory: 'Kategoria Konta',
    targetBranch: 'Sukurzál Destinu',
    cashBalance: 'Saldo Osan',
    valueUsd: 'Valór (USD)',
    commitEntry: 'Haruka Dadus',
    generatePdf: 'Print PDF Ofisiál',
    incomeStatement: 'Relatóriu Laba-Rugi',
    balanceSheet: 'Neraca',
    journal: 'Jornál Jerál',
    printTime: 'Tempu Print',
    auditedReport: 'Relatóriu Auditadu',
    fullName: 'Naran Kompletu',
    role: 'Papél',
    password: 'Password',
    newOperator: 'Operadór Foun',
    newBranch: 'Sukurzál Foun',
    location: 'Fatin',
    companyDetails: 'Detailu Kompania',
    persistenceLayer: 'Sekuransa Dadus',
    backup: 'Backup DB',
    restore: 'Restore',
    chartMatrix: 'Matriz Konta',
    newAccount: 'Konta Foun',
    allBranches: 'SUKURZÁL HOTU',
    mainHq: 'SENTRÁL',
    secureSession: 'SESAUN SEGURU',
    switchBranch: 'Troka Sukurzál',
    sessionLocked: 'Sesaun taka otomatis tanba la ativa'
  }
};