
-- ========================================================
-- SKRIP FINAL DATABASE AMIZADE ERP (VERSI FIX)
-- ========================================================

-- 1. BERSIHKAN TABEL LAMA (RESET TOTAL)
-- Menggunakan CASCADE untuk menghapus ketergantungan otomatis
DROP TABLE IF EXISTS audit_logs CASCADE;
DROP TABLE IF EXISTS ledger_entries CASCADE;
DROP TABLE IF EXISTS transactions CASCADE;
DROP TABLE IF EXISTS inventory_items CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS accounts CASCADE;
DROP TABLE IF EXISTS branches CASCADE;
DROP TABLE IF EXISTS settings CASCADE;

-- 2. BUAT TABEL BARU

-- A. Tabel Cabang
CREATE TABLE branches (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  location TEXT NOT NULL,
  code TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- B. Tabel User/Pengguna
CREATE TABLE users (
  id TEXT PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL, -- Di sini kita simpan plain text dulu untuk kemudahan awal
  name TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('ADMIN', 'USER')),
  branch_name TEXT, 
  avatar TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- C. Tabel Akun (Chart of Accounts)
CREATE TABLE accounts (
  code TEXT PRIMARY KEY,
  name_id TEXT NOT NULL,
  name_en TEXT NOT NULL,
  name_tet TEXT NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('ASSET', 'LIABILITY', 'EQUITY', 'REVENUE', 'EXPENSE', 'KASBON')),
  balance_type TEXT NOT NULL CHECK (balance_type IN ('DEBIT', 'CREDIT')),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- D. Tabel Transaksi Header
CREATE TABLE transactions (
  id TEXT PRIMARY KEY,
  date DATE NOT NULL DEFAULT CURRENT_DATE,
  description TEXT NOT NULL,
  reference_number TEXT,
  branch_name TEXT,
  user_id TEXT,
  status TEXT NOT NULL DEFAULT 'PENDING',
  type TEXT NOT NULL DEFAULT 'GENERAL',
  approved_by_user_id TEXT,
  is_hq_entry BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- E. Tabel Detail Jurnal (Ledger)
CREATE TABLE ledger_entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  transaction_id TEXT REFERENCES transactions(id) ON DELETE CASCADE,
  account_code TEXT NOT NULL,
  debit NUMERIC(15, 2) DEFAULT 0.00,
  credit NUMERIC(15, 2) DEFAULT 0.00,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- F. Tabel Inventaris/Kupon
CREATE TABLE inventory_items (
  id TEXT PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  category TEXT NOT NULL,
  reference_number TEXT,
  stock_in INTEGER DEFAULT 0,
  stock_out INTEGER DEFAULT 0,
  branch_name TEXT,
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- G. Tabel Pengaturan Aplikasi
CREATE TABLE settings (
  key_name TEXT PRIMARY KEY,
  value TEXT,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- H. Tabel Audit Log
CREATE TABLE audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  action TEXT NOT NULL,
  user_id TEXT,
  user_name TEXT,
  details TEXT,
  transaction_id TEXT,
  timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- 3. ISI DATA AWAL (SEEDING)

-- Isi Cabang (HQ dan Manufahi sebagai contoh)
INSERT INTO branches (id, name, location, code) VALUES
('BR-HQ', 'HEADQUARTERS', 'Dili, Timor-Leste', 'HQ'),
('BR-MNF', 'MANUFAHI', 'Same, Manufahi', 'MNF');

-- Isi User Admin (Username: admin, Password: password123)
INSERT INTO users (id, username, password_hash, name, role, branch_name) VALUES
('USR-ADMIN', 'admin', 'password123', 'Administrator', 'ADMIN', 'HEADQUARTERS');

-- Isi Chart of Accounts (COA) Standar
INSERT INTO accounts (code, name_id, name_en, name_tet, type, balance_type) VALUES
('1101', 'Kas Utama', 'Main Cash', 'Osan-inan', 'ASSET', 'DEBIT'),
('1201', 'Kasbon', 'Cash Advance', 'Kasbon', 'KASBON', 'DEBIT'),
('2201', 'Setoran Pusat', 'HQ Transfer', 'Transfersaun', 'LIABILITY', 'CREDIT'),
('4101', 'Pendapatan', 'Revenue', 'Rendimentu', 'REVENUE', 'CREDIT'),
('5101', 'Beban Operasional', 'Operational Expense', 'Kustu Operasional', 'EXPENSE', 'DEBIT'),
('5102', 'Gaji Pegawai', 'Salary Expense', 'Kustu Saláriu', 'EXPENSE', 'DEBIT'),
('5103', 'Sewa Tempat', 'Rent Expense', 'Kustu Aluga', 'EXPENSE', 'DEBIT'),
('5104', 'Listrik & Air', 'Utilities', 'Eletrisidade & Bee', 'EXPENSE', 'DEBIT');

-- Isi Pengaturan Awal Aplikasi
INSERT INTO settings (key_name, value) VALUES
('language', 'ID'),
('currency', 'USD'),
('dateFormat', 'DD/MM/YYYY'),
('companyName', 'LOTARIA AMIZADE'),
('isApprovalRequired', 'true');

-- 4. BUKA AKSES (PENTING UNTUK MODE PLUG-AND-PLAY)
-- Mematikan RLS agar aplikasi bisa langsung baca/tulis tanpa konfigurasi Policy yang rumit
ALTER TABLE branches DISABLE ROW LEVEL SECURITY;
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
ALTER TABLE accounts DISABLE ROW LEVEL SECURITY;
ALTER TABLE transactions DISABLE ROW LEVEL SECURITY;
ALTER TABLE ledger_entries DISABLE ROW LEVEL SECURITY;
ALTER TABLE inventory_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE settings DISABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs DISABLE ROW LEVEL SECURITY;

